"""empty message

Revision ID: 079248c56d9b
Revises: 7c60741b42eb
Create Date: 2019-05-29 21:42:06.932336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '079248c56d9b'
down_revision = '7c60741b42eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_author'), 'authors', ['author'], unique=False)
    op.create_table('m2m_authors',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], )
    )
    op.create_table('m2m_categories',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], )
    )
    op.drop_index('ix_athours_author', table_name='athours')
    op.drop_table('athours')
    op.add_column('orders', sa.Column('key', sa.Integer(), nullable=False))
    op.alter_column('orders', 'finish',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'finish',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('orders', 'key')
    op.create_table('athours',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('author', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_athours_author', 'athours', ['author'], unique=False)
    op.drop_table('m2m_categories')
    op.drop_table('m2m_authors')
    op.drop_index(op.f('ix_authors_author'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
