"""empty message

Revision ID: 1f9ee66a852e
Revises: 5bdfc71ab16d
Create Date: 2019-05-29 21:05:55.892653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f9ee66a852e'
down_revision = '5bdfc71ab16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.drop_index('s_email', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 's_email')
    op.drop_column('user', 's_pass')
    op.drop_column('user', 's_name')
    op.drop_column('user', 's_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('s_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('user', sa.Column('s_name', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('s_pass', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('user', sa.Column('s_email', mysql.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('s_email', 'user', ['s_email'], unique=True)
    op.drop_column('user', 'username')
    op.drop_column('user', 'password')
    op.drop_column('user', 'id')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
