"""empty message

Revision ID: 45d3bc6f1e29
Revises: b887a942a76b
Create Date: 2019-05-29 21:47:09.937816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45d3bc6f1e29'
down_revision = 'b887a942a76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m2m_categories')
    op.drop_table('m2m_authors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m2m_authors',
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='m2m_authors_ibfk_1'),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], name='m2m_authors_ibfk_2'),
    sa.PrimaryKeyConstraint('author_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('m2m_categories',
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], name='m2m_categories_ibfk_1'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='m2m_categories_ibfk_2'),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
