"""empty message

Revision ID: 5bdfc71ab16d
Revises: 
Create Date: 2019-05-29 21:04:26.183687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdfc71ab16d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('s_id', sa.Integer(), nullable=False),
    sa.Column('s_name', sa.String(length=64), nullable=True),
    sa.Column('s_email', sa.String(length=64), nullable=True),
    sa.Column('s_pass', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('s_id'),
    sa.UniqueConstraint('s_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
