"""empty message

Revision ID: b887a942a76b
Revises: 66f1c5a8601e
Create Date: 2019-05-29 21:45:15.524104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b887a942a76b'
down_revision = '66f1c5a8601e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m2m_authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('author_id'),
    primary_key=True
    )
    op.create_table('m2m_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    primary_key=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m2m_categories')
    op.drop_table('m2m_authors')
    # ### end Alembic commands ###
